### ISSUE TITLE
on scrape more data

### ISSUE THREAD

**Issue by brunobell** [allce231/qiushibaike#1]
Hi, it's a good try scraping and presenting contents from qiushibaike :+1: 
Yet I noticed that this project scrapes only the first 35 pages of the "text" category on the website.
Coincidently I've been working on a test project trying to scrape as much data as possible without being blocked by the server. I will push it to my repos list when finished. You're welcome to take a look when it's done. :D

**Comment by allce231** [comment]
You can open the url 'http://www.qiushibaike.com/' & get more url

**Comment by brunobell** [comment]
Sure I know, yet what I meant was to scrape as much articles as possible automatically.
Anyway, good try dude.
